name: sanity

on: push

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start Unifi Controller
        run: |
          # export DOCKER_NETWORK=${{ job.services.network }}
          ./unifi_controller.sh start
