name: sanity

on: push

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: sanity
        run: |
          export HOST_IP=$(ip route show | awk '/default/ {print $3}')
          ./unifi_controller.sh start
